print(
    '<AMO FAZER EXERCICIO NO URI>\n<    AMO FAZER EXERCICIO NO URI>\n<AMO FAZER EXERCICIO >\n<AMO FAZER EXERCICIO NO URI>\n<AMO FAZER EXERCICIO NO URI    >\n<AMO FAZER EXERCICIO NO URI>\n<          AMO FAZER EXERCICIO >\n<AMO FAZER EXERCICIO           >')
